"""Initial

Revision ID: 8b3c5cd7d820
Revises:
Create Date: 2026-01-29 23:43:39.945500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b3c5cd7d820"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("windows", sa.Text(), nullable=True),
        sa.Column("mac", sa.Text(), nullable=True),
        sa.Column("linux", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_modules_name"), "modules", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "clients",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("hostname", sa.Text(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum("windows", "mac", "linux", name="platform"),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=225), nullable=False),
        sa.Column("alive", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["owner_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_clients_owner_uuid"), "clients", ["owner_uuid"], unique=False
    )
    op.create_index(op.f("ix_clients_username"), "clients", ["username"], unique=True)
    op.create_table(
        "client_modules",
        sa.Column("client_uuid", sa.UUID(), nullable=False),
        sa.Column("module_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_uuid"], ["clients.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["module_uuid"], ["modules.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("client_uuid", "module_uuid"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("client_uuid", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_uuid"], ["clients.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("client_modules")
    op.drop_index(op.f("ix_clients_username"), table_name="clients")
    op.drop_index(op.f("ix_clients_owner_uuid"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_modules_name"), table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
